# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumcifun <- function(param, T_F, lower, upper) {
    .Call(`_art_cumcifun`, param, T_F, lower, upper)
}

cumcicurve <- function(param, T_F, lower, upper, npar) {
    .Call(`_art_cumcicurve`, param, T_F, lower, upper, npar)
}

eval_incirate <- function(param, T_F, t) {
    .Call(`_art_eval_incirate`, param, T_F, t)
}

eval_accuracy <- function(param, t) {
    .Call(`_art_eval_accuracy`, param, t)
}

