# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumcifun <- function(param, T_F, lower, upper) {
    .Call(`_art_cumcifun`, param, T_F, lower, upper)
}

cumcicurve <- function(param, T_F, lower, upper, npar) {
    .Call(`_art_cumcicurve`, param, T_F, lower, upper, npar)
}

eval_incirate <- function(param, T_F, t) {
    .Call(`_art_eval_incirate`, param, T_F, t)
}

eval_accuracy <- function(param, t) {
    .Call(`_art_eval_accuracy`, param, t)
}

eval_log_like <- function(param, T_F, t) {
    .Call(`_art_eval_log_like`, param, T_F, t)
}

get_loglike <- function(lambda_, theta_, z_, w_, gamma_, param_) {
    .Call(`_art_get_loglike`, lambda_, theta_, z_, w_, gamma_, param_)
}

rcpp_gen_surv_pp <- function(lambda_, theta_, z_, w_, gamma_, param_, item) {
    .Call(`_art_rcpp_gen_surv_pp`, lambda_, theta_, z_, w_, gamma_, param_, item)
}

rcpp_gen_surv_time <- function(lambda_, theta_, z_, w_, gamma_, param_, item) {
    .Call(`_art_rcpp_gen_surv_time`, lambda_, theta_, z_, w_, gamma_, param_, item)
}

rcpp_gen_surv <- function(lambda_, theta_, z_, w_, gamma_, param_, item) {
    .Call(`_art_rcpp_gen_surv`, lambda_, theta_, z_, w_, gamma_, param_, item)
}

