source("R/Renviron.R")
source('R/load-outputs.R')
## source('R/write_summary.R')
source('R/visual-latent-space-plot.R')
## source('R/visual-trace-plot.R')
## source('R/CIF_posm.R')
## source('R/CIF.R')
